layout_spectrum: 0.6401081
color:
  saturation: 0.2881109
  lightness: 0.0273077
  brandStrength: 0.2567793
  brandColors:
    - '#FFFFFF'
    - '#82A6C0'
    - '#D0D1CC'
    - '#736D61'
    - '#27281F'
  rhythmicContrast: 0.8350402
typography_spectrum: 0.5070721
name: AstaRudminaite
